version: '3.4'
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    environment: 
      ME_CONFIG_MONGODB_SERVER: 'mongo'
    ports:
      - 8081:8081

  hotel-review:
    links:
      - mongo
    restart: always
    command: ['npm', 'run', 'dev']
    ports: 
      - "3000:3000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./:/app